import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  teamsSidebar: [
    {
      type: 'doc',
      id: 'teams-overview',
      label: 'Teams & Ownership',
    },
    {
      type: 'category',
      label: 'Team Detail',
      items: [
        'teams/customer-services',
        'teams/operations',
        'teams/finance',
        'teams/field-services',
      ],
    },
    {
      type: 'category',
      label: 'Customer Services',
      items: [
        'persons/sarah-chen',
        'persons/marcus-rivera',
        'persons/aisha-patel',
        'persons/james-kowalski',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'persons/david-okonkwo',
        'persons/emily-zhang',
        'persons/raj-gupta',
        'persons/lisa-nakamura',
      ],
    },
    {
      type: 'category',
      label: 'Finance',
      items: [
        'persons/priya-sharma',
        'persons/carlos-mendez',
        'persons/anna-bergstrom',
        'persons/tom-ikeda',
      ],
    },
    {
      type: 'category',
      label: 'Field Services',
      items: [
        'persons/olga-petrov',
        'persons/kevin-brooks',
        'persons/maria-gonzalez',
        'persons/yusuf-ali',
      ],
    },
  ],
  usersSidebar: [
    {
      type: 'doc',
      id: 'users-overview',
      label: 'Users & Personas',
    },
    {
      type: 'category',
      label: 'Personas',
      items: [
        'personas/PER-001-utility-administrator',
        'personas/PER-002-treatment-operator',
        'personas/PER-003-residential-customer',
        'personas/PER-004-commercial-customer',
        'personas/PER-005-meter-technician',
      ],
    },
    {
      type: 'category',
      label: 'User Stories',
      link: {
        type: 'doc',
        id: 'user-stories/index',
      },
      items: [
        'user-stories/US-001-customer-enrollment',
        'user-stories/US-002-service-activation',
        'user-stories/US-004-meter-reading',
        'user-stories/US-005-view-usage-history',
        'user-stories/US-006-service-area-lookup',
        'user-stories/US-007-submit-service-request',
        'user-stories/US-008-technician-dispatch',
        'user-stories/US-009-customer-communication',
        'user-stories/US-010-smart-meter-integration',
      ],
    },
  ],
  systemSidebar: [
    {
      type: 'doc',
      id: 'system-overview',
      label: 'System Architecture',
    },
    {
      type: 'category',
      label: 'Bounded Contexts',
      link: {
        type: 'doc',
        id: 'systems/index',
      },
      items: [
        'systems/customer-account-mgmt',
        'systems/usage-tracking',
        'systems/billing-payments',
        'systems/meter-operations',
      ],
    },
    {
      type: 'category',
      label: 'Capabilities',
      link: {
        type: 'doc',
        id: 'capabilities/index',
      },
      items: [
        'capabilities/CAP-001',
        'capabilities/CAP-002',
        'capabilities/CAP-003',
        'capabilities/CAP-004',
        'capabilities/CAP-005',
        'capabilities/CAP-006',
        'capabilities/CAP-007',
        'capabilities/CAP-008',
      ],
    },
  ],
  practiceAreasSidebar: [
    {
      type: 'doc',
      id: 'practice-areas/index',
      label: 'Practice Areas Overview',
    },
    'practice-areas/PA-001-ddd',
    'practice-areas/PA-002-bdd',
    'practice-areas/PA-003-cloud',
    'practice-areas/PA-004-api',
    'practice-areas/PA-005-security',
    'practice-areas/PA-006-data',
  ],
  toolsSidebar: [
    {
      type: 'doc',
      id: 'tools/index',
      label: 'Technology Stack',
    },
    'tools/convex',
    'tools/nextjs',
    'tools/clerk',
    'tools/vercel',
    'tools/vitest',
    'tools/typescript',
  ],
  planningSidebar: [
    {
      type: 'category',
      label: '📋 Implementation Plans',
      link: {
        type: 'generated-index',
        title: 'Implementation Plans',
        description: 'Detailed implementation plans for roadmap items',
        slug: '/plans',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plans',
        },
      ],
    },
  ],
  dddSidebar: [
    {
      type: 'doc',
      id: 'ddd/domain-overview',
      label: 'Domain Overview',
    },
    {
      type: 'doc',
      id: 'ddd/bounded-contexts',
      label: 'Bounded Contexts',
    },
    {
      type: 'doc',
      id: 'ddd/ubiquitous-language',
      label: 'Ubiquitous Language',
    },
    {
      type: 'doc',
      id: 'ddd/aggregates-entities',
      label: 'Aggregates & Entities',
    },
    {
      type: 'doc',
      id: 'ddd/value-objects',
      label: 'Value Objects',
    },
    {
      type: 'doc',
      id: 'ddd/domain-events',
      label: 'Domain Events',
    },
    {
      type: 'doc',
      id: 'ddd/use-cases',
      label: 'Use Cases',
    },
    {
      type: 'doc',
      id: 'ddd/context-map',
      label: 'Context Map',
    },
    {
      type: 'doc',
      id: 'ddd/architecture-decisions',
      label: 'Architecture Decisions',
    },
  ],
  bddSidebar: [
    {
      type: 'doc',
      id: 'bdd/feature-index',
      label: 'Feature Index',
    },
    {
      type: 'doc',
      id: 'bdd/bdd-overview',
      label: 'BDD Overview',
    },
    {
      type: 'doc',
      id: 'bdd/gherkin-syntax',
      label: 'Gherkin Syntax',
    },
    {
      type: 'doc',
      id: 'bdd/ddd-bdd-mapping',
      label: 'DDD-BDD Mapping',
    },
    {
      type: 'doc',
      id: 'bdd/capability-tags',
      label: 'Capability Tags',
    },
  ],
  // capabilitiesSidebar: [
  //   {
  //     type: 'doc',
  //     id: 'capabilities/index',
  //     label: 'Capabilities Overview',
  //   },
  //   {
  //     type: 'category',
  //     label: 'Security',
  //     items: [
  //       'capabilities/CAP-001-authentication',
  //       'capabilities/CAP-004-rate-limiting',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Observability',
  //     items: [
  //       'capabilities/CAP-002-audit-logging',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Communication',
  //     items: [
  //       'capabilities/CAP-003-real-time-notifications',
  //     ],
  //   },
  // ],
  // userStoriesSidebar: [
  //   {
  //     type: 'doc',
  //     id: 'user-stories/index',
  //     label: 'User Stories Catalog',
  //   },
  //   {
  //     type: 'category',
  //     label: 'Bot Developer',
  //     items: [
  //       'user-stories/US-001-bot-registration',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Provider Bot',
  //     items: [
  //       'user-stories/US-002-promise-creation',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Consumer Bot',
  //     items: [
  //       'user-stories/US-004-promise-acceptance',
  //     ],
  //   },
  // ],
  agentsSidebar: [
    {
      type: 'doc',
      id: 'agents/overview',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'agents/quick-reference',
      label: 'Quick Reference',
    },
    {
      type: 'doc',
      id: 'agents/bdd-loop',
      label: 'BDD Loop Workflow',
    },
    {
      type: 'doc',
      id: 'agents/coordination',
      label: 'Agent Coordination',
    },
  ],
  roadsSidebar: [
    {
      type: 'doc',
      id: 'roads/index',
      label: '📋 Road Items Overview',
    },
    {
      type: 'category',
      label: 'Foundation (Phase 0)',
      items: [
        'roads/ROAD-001',
        'roads/ROAD-002',
        'roads/ROAD-003',
      ],
    },
    {
      type: 'category',
      label: 'Bot Identity (Phase 1)',
      items: [
        'roads/ROAD-004',
        'roads/ROAD-005',
        'roads/ROAD-006',
        'roads/ROAD-007',
      ],
    },
    {
      type: 'category',
      label: 'Token & Promise (Phase 2)',
      items: [
        'roads/ROAD-008',
        'roads/ROAD-009',
        'roads/ROAD-010',
        'roads/ROAD-011',
        'roads/ROAD-012',
        'roads/ROAD-013',
        'roads/ROAD-014',
      ],
    },
    {
      type: 'category',
      label: 'Settlement (Phase 3)',
      items: [
        'roads/ROAD-015',
        'roads/ROAD-016',
        'roads/ROAD-017',
        'roads/ROAD-018',
        'roads/ROAD-019',
        'roads/ROAD-020',
        'roads/ROAD-021',
        'roads/ROAD-022',
        'roads/ROAD-023',
        'roads/ROAD-024',
        'roads/ROAD-025',
        'roads/ROAD-026',
        'roads/ROAD-027',
        'roads/ROAD-028',
        'roads/ROAD-029',
        'roads/ROAD-030',
        'roads/ROAD-031',
        'roads/ROAD-032',
        'roads/ROAD-033',
        'roads/ROAD-034',
        'roads/ROAD-035',
        'roads/ROAD-036',
        'roads/ROAD-037',
      ],
    },
  ],
  adrSidebar: [
    {
      type: 'doc',
      id: 'adr/README',
      label: 'Architecture Decision Records',
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'adr/ADR-001',
        'adr/ADR-002',
        'adr/ADR-005',
        'adr/ADR-006',
        'adr/ADR-007',
        'adr/ADR-008',
        'adr/ADR-010',
        'adr/ADR-011',
        'adr/ADR-012',
        'adr/ADR-013',
        'adr/ADR-015',
        'adr/ADR-016',
        'adr/ADR-024',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [
        'adr/ADR-003',
        'adr/ADR-004',
        'adr/ADR-017',
        'adr/ADR-018',
        'adr/ADR-019',
        'adr/ADR-020',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'adr/ADR-009',
        'adr/ADR-021',
        'adr/ADR-022',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'adr/ADR-014',
        'adr/ADR-023',
      ],
    },
  ],
  nfrSidebar: [
    {
      type: 'doc',
      id: 'nfr/index',
      label: 'Non-Functional Requirements',
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'nfr/NFR-PERF-001',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'nfr/NFR-SEC-001',
      ],
    },
    {
      type: 'category',
      label: 'Accessibility',
      items: [
        'nfr/NFR-A11Y-001',
      ],
    },
  ],
  changesSidebar: [
    {
      type: 'doc',
      id: 'changes/changes-index',
      label: '📝 Change History',
    },
    {
      type: 'doc',
      id: 'changes/CHANGE-XXX',
      label: '📋 Change Template',
    },
    {
      type: 'category',
      label: '📦 Change Releases',
      link: {
        type: 'generated-index',
        title: 'Change Releases',
        description: 'Individual change entries with governance tracking',
        slug: '/changes/releases',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'changes',
        },
      ],
    },
  ],
};

export default sidebars;
